[package]
name = "tsubame-on-premises"
description = "The CMS with rkv (LMDB) storage and image files on local disk."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "tsubame"
path = "src/main.rs"

[dependencies]
tsubame-core = { path = "../core" }
argon2.workspace = true
rkv.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
tokio.workspace = true
axum.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
